import { reinventCloudItems } from "@/app/lib/reinvent.data";
import { trendingCloudItems } from "@/app/lib/trending.data";

import { cloudPartners } from "@/app/lib/partners.data";
import {
    GlobalHeader,
    GlobalHero,
    GlobalStats,
    GlobalReinvent,
    GlobalTrendingRail,
    GlobalCareer,
    GlobalHoverShowcase,
    PartnersWithText,
} from "@/app/components/common";
import { innovateItems } from "@/app/lib/hovers.data";
import OurTeamIntro from "@/app/components/common/our-team-intro";


export default function Industrial() {
    return (
        <div className="lg:px-10 bg-black text-white min-h-screen lg:py-16">
            <GlobalHeader
                title="Industrial"
                navItems={[
                    { label: "What we do", id: "what-we-do" },
                    { label: "Segments", id: "segment" },
                    { label: "What's trending", id: "whats-trending" },
                    { label: "Leaders", id: "leaders" },
                    { label: "Careers", id: "careers" },
                ]}
            />


            <GlobalHero
                id="what-we-do"
                title="Industrial consulting"
                description="Excelling at speed in industrial. A myriad of trends from technology shifts to evolving B2B customer expectations, software-driven product purpose, enhanced services and more are driving companies to embrace continuous reinvention. The time is now to redefine industrial business models."
                imageSrc="/images/industrial.svg"
            />


            <GlobalStats
                title="Industrial now"
                stats={[
                    {
                        value: "81%",
                        description:
                            "of time to market reductions can be achieved by using new technologies such as cloud, digital twins and agile engineering",
                    },
                    {
                        value: "90%",
                        description:
                            "of industrial customers see clear benefits in digitized B2B sales processes leading to a potential profitability increase",
                    },
                    {
                        value: "60%",
                        description:
                            "of the revenue of industrial companies will be generated by services in the next five to ten years",
                    },
                    {
                        value: "75%",
                        description:
                            "of industrial CEOs are upskilling their workforce for the future labor market due to the shift to autonomy and electrification",
                    },
                ]}
            />


            <GlobalReinvent
                title="How to reinvent industrial"
                items={reinventCloudItems}
                limit={8}
                className="lg:my-[120px]"
            />


            <GlobalHoverShowcase
                title="How to innovate"
                items={innovateItems}
            />



            <GlobalTrendingRail
                sectionId="whats-trending"
                title="What’s trending in industrial"
                items={trendingCloudItems}
                className="mt-24"
            />

            <PartnersWithText
                title="Partners in change"
                partners={cloudPartners}
                sectionId="partners"
                showLearnMore={false}
            />


            {/* <GlobalLeaders
                title="Our Leaders"
                leaders={leaders}
                sectionId="leaders"
                className="mt-24"
                imageSize="w-full lg:w-60 h-72"
            /> */}
            <OurTeamIntro
                    sectionId="team"
                    className="mt-24"
                     description={`We are Metasys, a global team of innovators, technologists, and strategists focused on
                      driving meaningful digital transformation. Across AI, cloud, data, and emerging technologies,
                      we collaborate to modernize systems, optimize operations, and deliver measurable business
                      impact. Our culture is built on innovation, technical excellence, and helping organizations
                      scale smarter, operate more efficiently, and embrace the future with confidence`}
                  />


            <GlobalCareer
                title="Industrial careers"
                description="The Industrial sector includes companies that help other businesses in manufacturing, shipping or producing their products. Help them reinvent by embracing continuous change.​​"
                mobileImage="/images/cloudbg.jpg"
                desktopImage="/images/cloudbg.jpg"
                sectionId="careers"
                className="mt-8"
                links={[
                    {
                        label: "Search open roles",
                        href: "/careers/search",
                    },
                ]}
            />
        </div>
    );
}
